// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agdpyzyukqcdgqywztpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZHB5enl1a3FjZGdxeXd6dHBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NjQ3MzcsImV4cCI6MjA1MTE0MDczN30.cZ_Z8iGhtTe5DtgVgnclwQZw-gkji894TzJOI2Frs-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);